# Generated by Django 3.2.8 on 2021-10-31 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0002_userprofile_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('OJ', 'Open to jobs'), ('HJ', 'Hires')], default='OJ', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
