# Generated by Django 3.2.8 on 2021-11-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0005_auto_20211102_2145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployerProfile',
            new_name='JobProfile',
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='recruitme/cv'),
        ),
    ]
