# Generated by Django 3.2.8 on 2021-11-13 14:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('recruitme_app', '0007_userprofile_hiring_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='requirements',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
