# Generated by Django 3.2.8 on 2021-11-14 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0008_jobprofile_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='description',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='recruitme/cv/profiles/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='recruitme/cv/applies/%Y/%m/%d')),
                ('coverletter', models.CharField(blank=True, max_length=511)),
                ('apply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitme_app.jobprofile')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitme_app.workerprofile')),
            ],
            options={
                'ordering': ['-apply_date'],
            },
        ),
    ]
