# Generated by Django 3.2.8 on 2021-11-15 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0009_auto_20211114_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='job',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='apply',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
