# Generated by Django 3.2.8 on 2021-11-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0011_alter_apply_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='skill',
            field=models.ManyToManyField(to='recruitme_app.SkillTag'),
        ),
    ]
