# Generated by Django 3.2.8 on 2021-12-02 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0012_auto_20211128_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltag',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
