# Generated by Django 3.2.8 on 2021-12-03 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0013_skilltag_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltag',
            name='owner',
        ),
        migrations.AddField(
            model_name='skilltag',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
