# Generated by Django 3.2.8 on 2021-12-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0014_auto_20211203_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='skill',
        ),
    ]
