# Generated by Django 3.2.8 on 2021-12-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0015_remove_workerprofile_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=255)),
                ('job', models.ManyToManyField(to='recruitme_app.JobProfile')),
            ],
        ),
    ]
