# Generated by Django 3.2.8 on 2021-12-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0016_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='job',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='recruitme/cv/applies/%Y/%m/%d'),
        ),
    ]
