# Generated by Django 3.2.8 on 2021-12-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0017_auto_20211205_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitme_app.jobprofile'),
        ),
    ]
