# Generated by Django 3.2.8 on 2021-12-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitme_app', '0018_alter_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='employer_comment',
            field=models.CharField(blank=True, max_length=511),
        ),
        migrations.AddField(
            model_name='apply',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apply',
            name='state',
            field=models.CharField(blank=True, choices=[('RJ', 'Rejected'), ('IP', 'In process')], max_length=20),
        ),
    ]
